#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to install nginx
apt-get -y update
apt-get -y install nginx
mkdir -p /var/www/html
echo "Holberton School" > "/var/www/html/index.html"
service nginx reload
service nginx restart
