#!/usr/bin/env bash
# Configure nginx with a redirect page

sudo apt-get update
sudo apt-get install Nginx -y
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "s/^\slocation \/ {$/\tlocation \/redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation \/ {/" /etc/nginx/sites-available/default
sudo service nginx restart
